name: Frontend linting

on:
  push:
    branches: [ main ]
    paths:
      - "app/frontend/**"
  pull_request:
    branches: [ main ]
    paths:
      - "app/frontend/**"

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
            - name: Run prettier on frontend
              run: |
                cd ./app/frontend
                npm install
                npx prettier --check .
